### ISSUE TITLE
GPU-accelerated prepfold

### ISSUE THREAD

**Issue by 0xCoto** [jintaoluo/presto_on_gpu#1]
Is it possible to GPU-accelerate a simple `prepfold` command for known pulsars?

**Comment by scottransom** [comment]
Probably with a lot of work.  But certainly not with the current code.  Making prepfold faster via parallelization has been on my ToDo list for a long time, but it isn't easy.  If you were interested in working on any of this, I'd be happy to help and accept patches!   :-)
